### ISSUE TITLE
Add new commands

### ISSUE THREAD

**Issue by CodeAlDente** [PPC-Trucking/V1#54]
**Players**
- [ ] `/carwhisper` Sends a text that only players can read who are in the same vehicle
- [ ] `/deposit` Make it easier to deposit money to your bank account
- [x] `/exit` Leave a house or business
- [ ] `/lights` Switch lights on / off if you are the driver of a vehicle
- [ ] `/setconfirm` Turn confirmation messages on / off _( only for current session, will later change to a permanent option, see also #81 )_
- [ ] `/setignore` Ignores a certain player so he can not send private messages to that player _( only for current session, will later change to a permanent option, see also #81 )_
- [ ] `/setpm` Turn private messages on / off _( only for current session, will later change to a permanent option, see also #81 )_
- [ ] `/removespike` Remove a spike manually, in addition to this increase the timer from 60 seconds (1 minute) to 180 seconds (3 minutes).
- [ ] `/whisper` Send a text that only player in your area (~ range: 15.0) can see
- [ ] `/withdraw` Make it easier to withdraw money from your bank account

**Admins**
- [x] `/announce` Displays a short message on screen (GameText) for all players (e.g. `/announce Hello World!`).
- [x] `/delpickup`
- [x] `/fuelall`
- [x] `/unfreeze`
- [x] `/setcash`
- [x] `/unjail` (`/jail` can only be used if player is not jailed so there is no workaround to get him out of jail anymore, we need a new command for that)
- [ ] `/freezed` to see all player that have been freezed

Additional to this:
- Do not forget to mention new commands on `/help`
- Also list them in the Wiki: [List of all available commands](../wiki/List-of-all-available-commands)
